[package]
name = "rusticdaemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustic_backend = "0.2.0"
rustic_core = "0.3.0"
simplelog = "0.12.2"
