# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Update Restic

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-restic-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for updates
        run: |
          ./scripts/update-restic-version.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update restic version"
          title: "chore: update restic version"
          branch: "update-restic-version"
          base: "main"
